In [2]:
from selenium import webdriver
import pandas as pd
import numpy as np

In [3]:
driver_path = "/Users/mmac/Desktop/PythonWorkspace2/chromedriver"
driver = webdriver.Chrome(executable_path=driver_path)

In [4]:
url = 'https://www.whoscored.com/Statistics'
#url = "http://www.google.com/"
driver.get(url)

In [22]:
def iteration_scrapping():
    """
    Xpath is very sensitive to current status of a website.
    Before running the code, each Xpath needs to be recalibrated
    
    """
    for i in range(1,11):
        rate_element = driver.find_elements_by_xpath('//*[@id="player-table-statistics-body"]/tr['+str(i)+']/td[13]')
        rate = [x.text for x in rate_element]
        rate_list.append(rate[0])
        player_element = driver.find_elements_by_xpath('/html/body/div[5]/div[3]/div[5]/div[1]/div[3]/div/table/tbody/tr['+str(i)+']/td[1]/a[1]')
        player = [x.text for x in player_element]
        player_list.append(player[0])

#Create 2 lists for ratings and the players        
rate_list = []
player_list = []

#Click on all players tab. This part finds and clicks on a specific div inside the page
all_players=driver.find_element_by_xpath('//*[@id="apps"]/dd[2]/a')
all_players.click()

#Scrape first page. This is a task specific code, it may not be necessary in different projects.
iteration_scrapping()

next_page=driver.find_element_by_xpath('/html/body/div[5]/div[3]/div[5]/div[1]/div[4]/div/dl[2]/dd[3]/a')
next_page.click() 

iteration_scrapping()

#Scrape the rest of the pages (233). Each page has 10 players.
#Sleep s necessary to wait until the page full loaded, otherwise an error will occur
import time

for i in range(1,234): 
    print(i)
    time.sleep(5)
    #click on next page option
    next_page=driver.find_element_by_xpath('/html/body/div[5]/div[3]/div[5]/div[1]/div[4]/div/dl[2]/dd[3]/a')
    next_page.click() 
    iteration_scrapping()

In [91]:
len(rate_list), len(player_list)

(2354, 2354)

In [92]:
#A couple of simple data wrangling 
df = pd.DataFrame([player_list,rate_list]).T

df.drop_duplicates(subset=None, keep='first', inplace=True)

df.iloc[1944:,:][0] = df.iloc[1944:,:][0].apply(lambda row : row[5:]) 

df = df.reset_index().drop('index', axis = 1)\
                .rename(columns = {0:'Player', 1:'Rating'})

In [103]:
df.head()

               Player Rating
0       Kylian Mbappé   8.46
1  Zlatan Ibrahimovic   8.41
2  Robert Lewandowski   8.28
3       Jack Grealish   8.11
4          Harry Kane   8.08

In [104]:
import pickle
pickle.dump(df, open( "player_ratings.p", "wb" ) )

In [105]:
pd.read_pickle('player_ratings.p')

                      Player Rating
0              Kylian Mbappé   8.46
1         Zlatan Ibrahimovic   8.41
2         Robert Lewandowski   8.28
3              Jack Grealish   8.11
4                 Harry Kane   8.08
5                     Neymar   7.93
6               Lionel Messi   7.85
7             Erling Haaland   7.83
8              Matheus Cunha   7.79
9           Domenico Berardi   7.72
10             Ángel Jiménez   8.24
11         Cristiano Ronaldo   8.17
12        Nico Schlotterbeck   7.92
13           Andrej Kramaric   7.85
14              Serge Aurier   7.73
15               Andy Delort   7.69
16     Dominic Calvert-Lewin   7.68
17           Bruno Fernandes   7.66
18             Son Heung-Min   7.66
19           Zinedine Ferhat   7.64
20                  Emre Can   7.63
21           James Rodríguez   7.63
22              Mats Hummels   7.62
23              Ben Chilwell   7.61
24            Ángel Di María   7.59
25             Thomas Müller   7.58
26            Joshua Kimmich   7.58
27             Gabriel Jesus   7.57
28             Romain Faivre   7.56
29              Lucas Alario   7.55
...                      ...    ...
2295      Jacob Bruun Larsen   5.82
2296           Dani Escriche   5.79
2297           Philipp Mwene   5.77
2298        Aboubakar Kamara   5.77
2299        Antonio Mazzotta   5.76
2300        Anastasios Donis   5.75
2301            Odion Ighalo   5.74
2302                  Danilo   5.74
2303  Aleksandar Radovanovic   5.72
2304              Koke Vegas   5.68
2305             Marek Rodák   5.65
2306   Lucas Martínez Quarta   5.59
2307                 Nícolas   5.58
2308            Pepe Sanchez   5.56
2309            Marcin Bulka   5.55
2310        Eduardo Henrique   5.55
2311      Ciprian Tatarusanu   5.54
2312              Ozan Kabak   5.54
2313            Eñaut Mendía   5.53
2314             Jeroen Zoet   5.53
2315             Eric Bailly   5.52
2316      Federico Marchetti   5.50
2317       Kepa Arrizabalaga   5.48
2318         Willy Caballero   5.41
2319            Kieran Gibbs   5.38
2320              Arne Maier   5.31
2321           Ralf Fährmann   5.30
2322                  Adrián   5.01
2323          Mitchell Dijks   4.98
2324  Bailey Peacock-Farrell   4.72

[2325 rows x 2 columns]

### Scrape 160k Players

In [ ]:
def player_rating(sira):
    url = 'https://www.whoscored.com/Players/'+ str(i)
    #url = "http://www.google.com/"
    driver.get(url)

    #İlk tablo
    #ilk tablo yani yıl ve maç detaylarının olduğu class burası.
    player_element = driver.find_elements_by_class_name("header-name")
    player = [x.text for x in player_element]
    position_element = driver.find_elements_by_class_name('position-table-entry')
    position = [x.text for x in position_element]
    rating_element = driver.find_elements_by_class_name('rating')
    rating = [x.text for x in rating_element]
    return player, position, rating

In [ ]:
player_dict = {}
for i in range(1,10000):
    if i % 100 == 0: 
        print(i)
    try:
        player, position, rating =  player_rating(i)
        player_dict[player[0]] = dict(zip(position[1:], rating))
    except:
        None